### ISSUE TITLE
cannot find credentials if AWS_PROFILE or AWS_DEFAULT_PROFILE environment vars are set

### ISSUE THREAD

**Issue by gjyoung1974** [lyft/python-blessclient#15]
if either:
AWS_PROFILE or AWS_DEFAULT_PROFILE is set, the client will not find aws credentials:

or if you run the command with the AWS_PROFILE env variable it will also fail to find the creds

AWS_PROFILE=dev ./blessclient.run --nocache --region WEST --config ~/bin/python-blessclient/conf/dev.cfg

Can't get your user information from AWS! Either you don't have your user aws credentials set as [default] in ~/.aws/credentials, or you have another process setting AWS credentials for a service account in your environment.Could not connect to BLESS in any configured region.

**Comment by gjyoung1974** [comment]
stack trace:
AWS_PROFILE=dev ./blessclient.run --nocache --region WEST --config ~/bin/python-blessclient/conf/dev.cfg
Traceback (most recent call last):
  File "/Users/gjyoung1974/bin/python-blessclient/blessclient.run", line 9, in <module>
    load_entry_point('blessclient==0.2.0', 'console_scripts', 'blessclient')()
  File "/Users/gjyoung1974/bin/python-blessclient/blessclient/client.py", line 621, in main
    bless(region, args.nocache, args.gui, args.host, bless_config)
  File "/Users/gjyoung1974/bin/python-blessclient/blessclient/client.py", line 428, in bless
    username = get_username(aws, bless_cache)
  File "/Users/gjyoung1974/bin/python-blessclient/blessclient/client.py", line 368, in get_username
    user = aws.iam_client().get_user()['User']
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    operation_model, request_dict)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 166, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 150, in create_request
    operation_name=operation_model.name)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/signers.py", line 154, in sign
    auth.add_auth(request)
  File "/Users/gjyoung1974/bin/python-blessclient/venv/lib/python2.7/site-packages/botocore/auth.py", line 340, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by Stype** [comment]
@gjyoung1974 just to clarify, when you're setting AWS_PROFILE=dev, do you want blessclient to access aws as that user? Or is the profile preventing your default user from being correctly used?

At Lyft we have users put their iam credentials in their default profile, so I've been considering unsetting AWS_PROFILE when users run bless. But if you're intentionally trying to run bless with that profile that won't work for you.

**Comment by gjyoung1974** [comment]
@Stype Sorry for much delay in response.
The issue was: if AWS_PROFILE=<anything> it causes blessclient to fail.
Presence of any profile, even the matching one is preventing your default user from being correctly used.

We wrote a wrapper script to call enrollment which does un-set the profile as a workaround.

**Comment by gjyoung1974** [comment]
This issue can be closed
