### ISSUE TITLE
ModuleNotFoundError: No module named 'awsmfautils'

### ISSUE THREAD

**Issue by bentterp** [lyft/python-blessclient#20]
Trying to set this up on my Centos7, using Python 3.6 from ius.io

Downloaded the master zip, and unpacked. After fiddling with requirements I got 'make client' to work
Successfully installed blessclient boto3-1.4.7 botocore-1.7.36 docutils-0.14 jmespath-0.9.3 kmsauth-0.2.0 psutil-5.4.0 python-dateutil-2.6.1 s3transfer-0.1.11 six-1.11.0
ln -s venv/bin/blessclient ./blessclient.run

But actually running the result fails:
[bent@c7vm python-blessclient-master]$ ./blessclient.run
Traceback (most recent call last):
  File "./blessclient.run", line 11, in <module>
    load_entry_point('blessclient', 'console_scripts', 'blessclient')()
  File "/tmp/python-blessclient-master/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/python-blessclient-master/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/tmp/python-blessclient-master/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/tmp/python-blessclient-master/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/python-blessclient-master/blessclient/client.py", line 22, in <module>
    import awsmfautils
ModuleNotFoundError: No module named 'awsmfautils'
[bent@c7vm python-blessclient-master]$

Should I package the contents of the venv somehow and install that?

**Comment by Stype** [comment]
Hi @bentterp, I'm going to suspect that running under python 3.6 is causing the issue. Blessclient is tested (and at Lyft runs for everyone) using python 2.7. Try that out, and let me know if you're still seeing issues!

Python3 support would be awesome, and should be fairly easy to do. I just haven't had the time.

**Comment by asottile** [comment]
I originally added python3 support in #25 and I'm making it _actually work_ in #33 :)
